"""Optimize scan_alerts indexes for faster bulk inserts

Revision ID: 6336603e94cd
Revises: b426481be371
Create Date: 2025-10-21 20:19:38.198150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6336603e94cd'
down_revision: Union[str, Sequence[str], None] = 'b426481be371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_alerts_alert_name'), table_name='scan_alerts')
    op.drop_index(op.f('ix_scan_alerts_confidence'), table_name='scan_alerts')
    op.drop_index(op.f('ix_scan_alerts_created_at'), table_name='scan_alerts')
    op.drop_index(op.f('ix_scan_alerts_cwe_id'), table_name='scan_alerts')
    op.drop_index(op.f('ix_scan_alerts_id'), table_name='scan_alerts')
    op.drop_index(op.f('ix_scan_alerts_risk_level'), table_name='scan_alerts')
    op.drop_index(op.f('ix_scan_alerts_url'), table_name='scan_alerts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_scan_alerts_url'), 'scan_alerts', ['url'], unique=False)
    op.create_index(op.f('ix_scan_alerts_risk_level'), 'scan_alerts', ['risk_level'], unique=False)
    op.create_index(op.f('ix_scan_alerts_id'), 'scan_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_scan_alerts_cwe_id'), 'scan_alerts', ['cwe_id'], unique=False)
    op.create_index(op.f('ix_scan_alerts_created_at'), 'scan_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_scan_alerts_confidence'), 'scan_alerts', ['confidence'], unique=False)
    op.create_index(op.f('ix_scan_alerts_alert_name'), 'scan_alerts', ['alert_name'], unique=False)
    # ### end Alembic commands ###
