"""Add priority field and optimize indexes

Revision ID: 9b4ca5199cd8
Revises: b37ca55f8b1b
Create Date: 2025-10-21 19:52:11.571626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9b4ca5199cd8'
down_revision: Union[str, Sequence[str], None] = 'b37ca55f8b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_scan_alerts_confidence'), 'scan_alerts', ['confidence'], unique=False)
    op.create_index(op.f('ix_scan_alerts_created_at'), 'scan_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_scan_alerts_cwe_id'), 'scan_alerts', ['cwe_id'], unique=False)
    op.create_index(op.f('ix_scan_alerts_id'), 'scan_alerts', ['id'], unique=False)
    op.create_index('ix_scan_alerts_scan_created', 'scan_alerts', ['scan_id', 'created_at'], unique=False)
    op.create_index('ix_scan_alerts_scan_risk', 'scan_alerts', ['scan_id', 'risk_level'], unique=False)
    op.create_index(op.f('ix_scan_alerts_url'), 'scan_alerts', ['url'], unique=False)
    op.add_column('scans', sa.Column('priority', sa.Integer(), nullable=False, server_default='5'))
    op.create_index(op.f('ix_scans_id'), 'scans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_id'), table_name='scans')
    op.drop_column('scans', 'priority')
    op.drop_index(op.f('ix_scan_alerts_url'), table_name='scan_alerts')
    op.drop_index('ix_scan_alerts_scan_risk', table_name='scan_alerts')
    op.drop_index('ix_scan_alerts_scan_created', table_name='scan_alerts')
    op.drop_index(op.f('ix_scan_alerts_id'), table_name='scan_alerts')
    op.drop_index(op.f('ix_scan_alerts_cwe_id'), table_name='scan_alerts')
    op.drop_index(op.f('ix_scan_alerts_created_at'), table_name='scan_alerts')
    op.drop_index(op.f('ix_scan_alerts_confidence'), table_name='scan_alerts')
    # ### end Alembic commands ###
