"""Remove priority field from scans table

Revision ID: b426481be371
Revises: 9b4ca5199cd8
Create Date: 2025-10-21 20:03:39.578525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b426481be371'
down_revision: Union[str, Sequence[str], None] = '9b4ca5199cd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('priority', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
